### PR TITLE
Adding case breaks for jshint

### PR DESCRIPTION
**Pull request by jackspirou**
This pull request adds case `break`s where linters expect them.

### CODE REVIEW

**Comment by garycourt** [comment]
This breaks the hash logic (no pun intended). There is a reason that the breaks aren't there, you know.

**Comment by jackspirou** [comment]
@garycourt thanks for the quick reply!  I haven't taken the time to go through the logic, but yeah I was afraid of that... 

Out of curiosity would moving the code below after the switch statement allow the additions of the `break` and keep the proper logic? 

``` javascript
k1 = (((k1 & 0xffff) * c1) + ((((k1 >>> 16) * c1) & 0xffff) << 16)) & 0xffffffff;
    k1 = (k1 << 15) | (k1 >>> 17);
    k1 = (((k1 & 0xffff) * c2) + ((((k1 >>> 16) * c2) & 0xffff) << 16)) & 0xffffffff;
    h1 ^= k1;
```

Again thanks for the response and explanation!

**Comment by garycourt** [comment]
No. I would just turn off break checking in your linter. While most people's code need them, there are legitimate reasons for not using breaks with switches - and this code takes advantage of that to keep the code small and fast.

**Comment by jackspirou** [comment]
Sounds good.  Thanks!

**Pull request closed without merging**
